apiVersion: v1
kind: Pod
metadata:
  name: dashboard
  namespace: infra
  annotations:
    vkube.io/network: gt
    vkube.io/image-policy: auto
    vkube.io/aliases: "dashboard"
spec:
  restartPolicy: Always
  volumes:
    - name: config
      configMap:
        name: dashboard-config
  containers:
    - name: dashboard
      image: 192.168.200.3:5000/mkube-dashboard:edge
      startupProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 2
        periodSeconds: 2
        failureThreshold: 10
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        periodSeconds: 30
        failureThreshold: 3
      volumeMounts:
        - name: config
          mountPath: /etc/dashboard
